/*
 * Jobs API 2.1
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.edmunds.rest.databricks.DTO.libraries;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * RCranLibraryDTO
 */
@JsonPropertyOrder({
  RCranLibraryDTO.JSON_PROPERTY_PACKAGE,
  RCranLibraryDTO.JSON_PROPERTY_REPO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2022-03-10T00:34:34.435-08:00[America/Los_Angeles]")
public class RCranLibraryDTO {
  public static final String JSON_PROPERTY_PACKAGE = "package";
  @JsonProperty(JSON_PROPERTY_PACKAGE)
  private String _package;

  public static final String JSON_PROPERTY_REPO = "repo";
  @JsonProperty(JSON_PROPERTY_REPO)
  private String repo;

  public RCranLibraryDTO _package(String _package) {
    this._package = _package;
    return this;
  }

  /**
   * The name of the CRAN package to install. This field is required.
   * @return _package
   **/
  @JsonProperty(value = "package")

  public String getPackage() {
    return _package;
  }

  public void setPackage(String _package) {
    this._package = _package;
  }

  public RCranLibraryDTO repo(String repo) {
    this.repo = repo;
    return this;
  }

  /**
   * The repository where the package can be found. If not specified, the default CRAN repo is used.
   * @return repo
   **/
  @JsonProperty(value = "repo")

  public String getRepo() {
    return repo;
  }

  public void setRepo(String repo) {
    this.repo = repo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RCranLibraryDTO rcranLibrary = (RCranLibraryDTO) o;
    return Objects.equals(this._package, rcranLibrary._package) &&
        Objects.equals(this.repo, rcranLibrary.repo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_package, repo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RCranLibraryDTO {\n");
    
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

