/*
 * Jobs API 2.1
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.edmunds.rest.databricks.DTO.jobs;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * JobCluster
 */
@JsonPropertyOrder({
        JobCluster.JSON_PROPERTY_JOB_CLUSTER_KEY,
        JobCluster.JSON_PROPERTY_NEW_CLUSTER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2022-03-09T23:53:34.566-08:00[America/Los_Angeles]")
public class JobCluster {
    public static final String JSON_PROPERTY_JOB_CLUSTER_KEY = "job_cluster_key";
    public static final String JSON_PROPERTY_NEW_CLUSTER = "new_cluster";
    @JsonProperty(JSON_PROPERTY_JOB_CLUSTER_KEY)
    private String jobClusterKey;
    @JsonProperty(JSON_PROPERTY_NEW_CLUSTER)
    private NewClusterDTO newCluster;

    public JobCluster jobClusterKey(String jobClusterKey) {
        this.jobClusterKey = jobClusterKey;
        return this;
    }

    /**
     * A unique name for the job cluster. This field is required and must be unique within the job. &#x60;JobTaskSettings&#x60; may refer to this field to determine which cluster to launch for the task execution.
     *
     * @return jobClusterKey
     **/
    @JsonProperty(value = "job_cluster_key")
    public String getJobClusterKey() {
        return jobClusterKey;
    }

    public void setJobClusterKey(String jobClusterKey) {
        this.jobClusterKey = jobClusterKey;
    }

    public JobCluster newCluster(NewClusterDTO newCluster) {
        this.newCluster = newCluster;
        return this;
    }

    /**
     * Get newCluster
     *
     * @return newCluster
     **/
    @JsonProperty(value = "new_cluster")
    public NewClusterDTO getNewCluster() {
        return newCluster;
    }

    public void setNewCluster(NewClusterDTO newCluster) {
        this.newCluster = newCluster;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobCluster jobCluster = (JobCluster) o;
        return Objects.equals(this.jobClusterKey, jobCluster.jobClusterKey) &&
                Objects.equals(this.newCluster, jobCluster.newCluster);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jobClusterKey, newCluster);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobCluster {\n");

        sb.append("    jobClusterKey: ").append(toIndentedString(jobClusterKey)).append("\n");
        sb.append("    newCluster: ").append(toIndentedString(newCluster)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

