/*
 * Jobs API 2.1
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.edmunds.rest.databricks.DTO.jobs;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SparkJarTaskDTO
 */
@JsonPropertyOrder({
        SparkJarTaskDTO.JSON_PROPERTY_MAIN_CLASS_NAME,
        SparkJarTaskDTO.JSON_PROPERTY_PARAMETERS,
        SparkJarTaskDTO.JSON_PROPERTY_JAR_URI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2022-03-09T23:53:34.566-08:00[America/Los_Angeles]")
public class SparkJarTaskDTO {
    public static final String JSON_PROPERTY_MAIN_CLASS_NAME = "main_class_name";
    public static final String JSON_PROPERTY_PARAMETERS = "parameters";
    public static final String JSON_PROPERTY_JAR_URI = "jar_uri";
    @JsonProperty(JSON_PROPERTY_MAIN_CLASS_NAME)
    private String mainClassName;
    @JsonProperty(JSON_PROPERTY_PARAMETERS)
    private List<String> parameters = null;
    @JsonProperty(JSON_PROPERTY_JAR_URI)
    private String jarUri;

    public SparkJarTaskDTO mainClassName(String mainClassName) {
        this.mainClassName = mainClassName;
        return this;
    }

    /**
     * The full name of the class containing the main method to be executed. This class must be contained in a JAR provided as a library.  The code must use &#x60;SparkContext.getOrCreate&#x60; to obtain a Spark context; otherwise, runs of the job fail.
     *
     * @return mainClassName
     **/
    @JsonProperty(value = "main_class_name")

    public String getMainClassName() {
        return mainClassName;
    }

    public void setMainClassName(String mainClassName) {
        this.mainClassName = mainClassName;
    }

    public SparkJarTaskDTO parameters(List<String> parameters) {
        this.parameters = parameters;
        return this;
    }

    public SparkJarTaskDTO addParametersItem(String parametersItem) {
        if (this.parameters == null) {
            this.parameters = new ArrayList<String>();
        }
        this.parameters.add(parametersItem);
        return this;
    }

    /**
     * Parameters passed to the main method.  Use [Task parameter variables](https://docs.microsoft.com/azure/databricks/jobs#parameter-variables) to set parameters containing information about job runs.
     *
     * @return parameters
     **/
    @JsonProperty(value = "parameters")

    public List<String> getParameters() {
        return parameters;
    }

    public void setParameters(List<String> parameters) {
        this.parameters = parameters;
    }

    public SparkJarTaskDTO jarUri(String jarUri) {
        this.jarUri = jarUri;
        return this;
    }

    /**
     * Deprecated since 04/2016\\. Provide a &#x60;jar&#x60; through the &#x60;libraries&#x60; field instead. For an example, see [Create](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/jobs#operation/JobsCreate).
     *
     * @return jarUri
     **/
    @JsonProperty(value = "jar_uri")

    public String getJarUri() {
        return jarUri;
    }

    public void setJarUri(String jarUri) {
        this.jarUri = jarUri;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SparkJarTaskDTO sparkJarTask = (SparkJarTaskDTO) o;
        return Objects.equals(this.mainClassName, sparkJarTask.mainClassName) &&
                Objects.equals(this.parameters, sparkJarTask.parameters) &&
                Objects.equals(this.jarUri, sparkJarTask.jarUri);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mainClassName, parameters, jarUri);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SparkJarTaskDTO {\n");

        sb.append("    mainClassName: ").append(toIndentedString(mainClassName)).append("\n");
        sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
        sb.append("    jarUri: ").append(toIndentedString(jarUri)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

