/*
 * Copyright 2018 Edmunds.com, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.edmunds.rest.databricks.DTO.clusters;

import java.io.Serializable;

/**
 * @see <a href="https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterterminationreasonterminationcode">https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterterminationreasonterminationcode</a>
 */
public enum TerminationCodeDTO implements Serializable {
    USER_REQUEST("USER_REQUEST"),
    JOB_FINISHED("JOB_FINISHED"),
    INACTIVITY("INACTIVITY"),
    CLOUD_PROVIDER_SHUTDOWN("CLOUD_PROVIDER_SHUTDOWN"),
    COMMUNICATION_LOST("COMMUNICATION_LOST"),
    CLOUD_PROVIDER_LAUNCH_FAILURE("CLOUD_PROVIDER_LAUNCH_FAILURE"),
    SPARK_IMAGE_DOWNLOAD_FAILURE("SPARK_IMAGE_DOWNLOAD_FAILURE"),
    SPOT_INSTANCE_TERMINATION("SPOT_INSTANCE_TERMINATION"),
    SPARK_STARTUP_FAILURE("SPARK_STARTUP_FAILURE"),
    INVALID_ARGUMENT("INVALID_ARGUMENT"),
    UNEXPECTED_LAUNCH_FAILURE("UNEXPECTED_LAUNCH_FAILURE"),
    INTERNAL_ERROR("INTERNAL_ERROR"),
    SPARK_ERROR("SPARK_ERROR"),
    METASTORE_COMPONENT_UNHEALTHY("METASTORE_COMPONENT_UNHEALTHY"),
    DBFS_COMPONENT_UNHEALTHY("DBFS_COMPONENT_UNHEALTHY"),
    AWS_AUTHORIZATION_FAILURE("AWS_AUTHORIZATION_FAILURE"),
    AWS_INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET_FAILURE("AWS_INSUFFICIENT_FREE_ADDRESSES_IN_SUBNET_FAILURE"),
    AWS_INSUFFICIENT_INSTANCE_CAPACITY_FAILURE("AWS_INSUFFICIENT_INSTANCE_CAPACITY_FAILURE"),
    AWS_MAX_SPOT_INSTANCE_COUNT_EXCEEDED_FAILURE("AWS_MAX_SPOT_INSTANCE_COUNT_EXCEEDED_FAILURE"),
    AWS_REQUEST_LIMIT_EXCEEDED("AWS_REQUEST_LIMIT_EXCEEDED"),
    AWS_UNSUPPORTED_FAILURE("AWS_UNSUPPORTED_FAILURE"),
    AZURE_BYOK_KEY_PERMISSION_FAILURE("AZURE_BYOK_KEY_PERMISSION_FAILURE"),
    AZURE_EPHEMERAL_DISK_FAILURE("AZURE_EPHEMERAL_DISK_FAILURE"),
    AZURE_INVALID_DEPLOYMENT_TEMPLATE("AZURE_INVALID_DEPLOYMENT_TEMPLATE"),
    AZURE_OPERATION_NOT_ALLOWED_EXCEPTION("AZURE_OPERATION_NOT_ALLOWED_EXCEPTION"),
    AZURE_QUOTA_EXCEEDED_EXCEPTION("AZURE_QUOTA_EXCEEDED_EXCEPTION"),
    AZURE_UNEXPECTED_DEPLOYMENT_TEMPLATE_FAILURE("AZURE_UNEXPECTED_DEPLOYMENT_TEMPLATE_FAILURE"),
    AZURE_VM_EXTENSION_FAILURE("AZURE_VM_EXTENSION_FAILURE"),
    AZURE_VNET_CONFIGURATION_FAILURE("AZURE_VM_EXTENSION_FAILURE"),
    AZURE_RESOURCE_PROVIDER_THROTTLING("AZURE_RESOURCE_PROVIDER_THROTTLING"),
    AZURE_RESOURCE_MANAGER_THROTTLING("AZURE_RESOURCE_MANAGER_THROTTLING"),
    NETWORK_CONFIGURATION_FAILURE("NETWORK_CONFIGURATION_FAILURE"),
    DRIVER_UNREACHABLE("DRIVER_UNREACHABLE"),
    DRIVER_UNRESPONSIVE("DRIVER_UNRESPONSIVE"),
    INSTANCE_UNREACHABLE("INSTANCE_UNREACHABLE"),
    CONTAINER_LAUNCH_FAILURE("CONTAINER_LAUNCH_FAILURE"),
    INSTANCE_POOL_CLUSTER_FAILURE("INSTANCE_POOL_CLUSTER_FAILURE"),
    REQUEST_REJECTED("REQUEST_REJECTED"),
    INIT_SCRIPT_FAILURE("INIT_SCRIPT_FAILURE"),
    TRIAL_EXPIRED("TRIAL_EXPIRED"),
    ABUSE_DETECTED("ABUSE_DETECTED"),
    ATTACH_PROJECT_FAILURE("ATTACH_PROJECT_FAILURE"),
    BOOTSTRAP_TIMEOUT("BOOTSTRAP_TIMEOUT"),
    BOOTSTRAP_TIMEOUT_CLOUD_PROVIDER_EXCEPTION("BOOTSTRAP_TIMEOUT_CLOUD_PROVIDER_EXCEPTION"),
    CLOUD_PROVIDER_DISK_SETUP_FAILURE("CLOUD_PROVIDER_DISK_SETUP_FAILURE"),
    CONTROL_PLANE_REQUEST_FAILURE("CONTROL_PLANE_REQUEST_FAILURE"),
    DATABASE_CONNECTION_FAILURE("DATABASE_CONNECTION_FAILURE"),
    DOCKER_IMAGE_PULL_FAILURE("DOCKER_IMAGE_PULL_FAILURE"),
    EXECUTION_COMPONENT_UNHEALTHY("EXECUTION_COMPONENT_UNHEALTHY"),
    GCP_QUOTA_EXCEEDED("GCP_QUOTA_EXCEEDED"),
    GCP_SERVICE_ACCOUNT_DELETED("GCP_SERVICE_ACCOUNT_DELETED"),
    HIVE_METASTORE_PROVISIONING_FAILURE("HIVE_METASTORE_PROVISIONING_FAILURE"),
    IMAGE_PULL_PERMISSION_DENIED("IMAGE_PULL_PERMISSION_DENIED"),
    INVALID_SPARK_IMAGE("INVALID_SPARK_IMAGE"),
    IP_EXHAUSTION_FAILURE("IP_EXHAUSTION_FAILURE"),
    K8S_AUTOSCALING_FAILURE("K8S_AUTOSCALING_FAILURE"),
    K8S_DBR_CLUSTER_LAUNCH_TIMEOUT("K8S_DBR_CLUSTER_LAUNCH_TIMEOUT"),
    NEPHOS_RESOURCE_MANAGEMENT("NEPHOS_RESOURCE_MANAGEMENT"),
    NFS_MOUNT_FAILURE("NFS_MOUNT_FAILURE"),
    NPIP_TUNNEL_SETUP_FAILURE("NPIP_TUNNEL_SETUP_FAILURE"),
    NPIP_TUNNEL_TOKEN_FAILURE("NPIP_TUNNEL_TOKEN_FAILURE"),
    REQUEST_THROTTLED("REQUEST_THROTTLED"),
    SECRET_RESOLUTION_ERROR("SECRET_RESOLUTION_ERROR"),
    SECURITY_DAEMON_REGISTRATION_EXCEPTION("SECURITY_DAEMON_REGISTRATION_EXCEPTION"),
    SELF_BOOTSTRAP_FAILURE("SELF_BOOTSTRAP_FAILURE"),
    SKIPPED_SLOW_NODES("SKIPPED_SLOW_NODES"),
    SLOW_IMAGE_DOWNLOAD("SLOW_IMAGE_DOWNLOAD"),
    STORAGE_DOWNLOAD_FAILURE("STORAGE_DOWNLOAD_FAILURE"),
    STS_CLIENT_SETUP_FAILURE("STS_CLIENT_SETUP_FAILURE"),
    SUBNET_EXHAUSTED_FAILURE("SUBNET_EXHAUSTED_FAILURE"),
    TEMPORARILY_UNAVAILABLE("TEMPORARILY_UNAVAILABLE"),
    UNKNOWN("UNKNOWN"),
    UNSUPPORTED_INSTANCE_TYPE("UNSUPPORTED_INSTANCE_TYPE"),
    UPDATE_INSTANCE_PROFILE_FAILURE("UPDATE_INSTANCE_PROFILE_FAILURE"),
    WORKER_SETUP_FAILURE("WORKER_SETUP_FAILURE"),
    WORKSPACE_CANCELLED_ERROR("WORKSPACE_CANCELLED_ERROR"),
    WORKSPACE_CONFIGURATION_ERROR("WORKSPACE_CONFIGURATION_ERROR"),
    CLOUD_PROVIDER_RESOURCE_STOCKOUT("CLOUD_PROVIDER_RESOURCE_STOCKOUT"),
    GLOBAL_INIT_SCRIPT_FAILURE("GLOBAL_INIT_SCRIPT_FAILURE");

    private String value;

    TerminationCodeDTO(String value) {
        this.value = value;
    }

    public String toString() {
        return this.value;
    }
}
